# Generated by Django 4.1.2 on 2022-11-18 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=30, unique=True)),
                ('curso', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_Equipo', models.IntegerField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=15)),
                ('especificaciones', models.TextField(max_length=150)),
                ('proveedor', models.CharField(max_length=30)),
                ('detalles', models.TextField(max_length=150)),
                ('fecha_compra', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=30, unique=True)),
                ('departamento', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemapregunta', models.TextField(default='disco', max_length=1000)),
                ('solucion', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.IntegerField(primary_key=True, serialize=False)),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceApp.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='serviceApp.ticket')),
                ('fecha_mantencion', models.DateField(auto_now=True)),
            ],
            bases=('serviceApp.ticket',),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='serviceApp.ticket')),
                ('fecha_reserva', models.DateTimeField(auto_now=True)),
            ],
            bases=('serviceApp.ticket',),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_despacho', models.DateField(auto_now_add=True)),
                ('id_equipo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='serviceApp.equipo')),
            ],
        ),
    ]
