# Generated by Django 4.1.2 on 2022-11-18 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='rut',
        ),
        migrations.AddField(
            model_name='mantencion',
            name='rut',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='serviceApp.alumno'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='rut',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='serviceApp.alumno'),
        ),
    ]
