# Generated by Django 4.1.2 on 2022-11-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0002_remove_ticket_rut_mantencion_rut_reserva_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='id_Equipo',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
