# Generated by Django 4.1.2 on 2022-12-06 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0004_mantencion_problema_mantencion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='rut',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='serviceApp.alumno'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateField(auto_now=True),
        ),
    ]
