# Generated by Django 4.1.2 on 2022-12-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0005_prestamo_rut_alter_reserva_fecha_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='id_prestamo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
